In [35]:
from data_loader import DataLoader
from constants import *
from decision_tree_creator import DecisionTreeCreator
from tree import *
from evaluator import Evaluator


In [27]:
len(np.loadtxt(clean_dataset))

2000

In [28]:
dl = DataLoader(clean_dataset)
cross_val_sets = dl.get_cross_validation_arr()
dl.dataset


array([[-57., -53., -50., ..., -83., -82.,   4.],
       [-64., -56., -58., ..., -88., -84.,   1.],
       [-44., -53., -51., ..., -84., -76.,   3.],
       ...,
       [-61., -62., -64., ..., -81., -90.,   1.],
       [-60., -51., -59., ..., -81., -76.,   1.],
       [-59., -52., -49., ..., -83., -81.,   4.]])

In [29]:
train, val, test = cross_val_sets[0]
len(train)

1200

In [32]:
dtc = DecisionTreeCreator()
tree = dtc.learn(dl.dataset)
tree.depth

12

In [37]:
evaluator = Evaluator(test_data=test, tree=tree)
evaluator.evaluate()

confusion matrix: 
[[ 96.   0.   0.   0.]
 [  0. 106.   4.   0.]
 [  0.   4.  86.   0.]
 [  0.   0.   0. 104.]]
accuracy: 0.98
precision: [1.         0.96363636 0.95555556 1.        ]
recall: [1.         0.96363636 0.95555556 1.        ]
f1_measure: [1.         0.96363636 0.95555556 1.        ]
